#############################################################################
# Makefile for building: webbrowser.app/Contents/MacOS/webbrowser
# Generated by qmake (2.01a) (Qt 4.7.3) on: ti toukokuuta 3 19:02:46 2011
# Project:  webbrowser.pro
# Template: app
# Command: /Users/anskosti/QtSDK/Desktop/Qt/473/gcc/bin/qmake -o Makefile webbrowser.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DNETWORKACCESS -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/default -I. -I../../../QtSDK/Desktop/Qt/473/gcc/lib/QtCore.framework/Versions/4/Headers -I../../../QtSDK/Desktop/Qt/473/gcc/include/QtCore -I../../../QtSDK/Desktop/Qt/473/gcc/lib/QtGui.framework/Versions/4/Headers -I../../../QtSDK/Desktop/Qt/473/gcc/include/QtGui -I../../../QtSDK/Desktop/Qt/473/gcc/lib/QtDeclarative.framework/Versions/4/Headers -I../../../QtSDK/Desktop/Qt/473/gcc/include/QtDeclarative -I../../../QtSDK/Desktop/Qt/473/gcc/include -Iqmlapplicationviewer -I. -F/Users/anskosti/QtSDK/Desktop/Qt/473/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/anskosti/QtSDK/Desktop/Qt/473/gcc/lib -L/Users/anskosti/QtSDK/Desktop/Qt/473/gcc/lib -framework QtDeclarative -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/anskosti/QtSDK/Desktop/Qt/473/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		qmlapplicationviewer/qmlapplicationviewer.cpp moc_qmlapplicationviewer.cpp
OBJECTS       = main.o \
		qmlapplicationviewer.o \
		moc_qmlapplicationviewer.o
DIST          = ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf \
		webbrowser.pro
QMAKE_TARGET  = webbrowser
DESTDIR       = 
TARGET        = webbrowser.app/Contents/MacOS/webbrowser

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile webbrowser.app/Contents/PkgInfo webbrowser.app/Contents/Resources/empty.lproj webbrowser.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) webbrowser.app/Contents/MacOS/ || $(MKDIR) webbrowser.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: webbrowser.pro  ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/default/qmake.conf ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile webbrowser.pro
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac.conf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/mac-g++.conf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_pre.prf:
qmlapplicationviewer/qmlapplicationviewer.pri:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/dwarf2.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/debug.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/default_post.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/x86_64.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/objective_c.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/rez.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/mac/sdk.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf:
../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile webbrowser.pro

webbrowser.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) webbrowser.app/Contents || $(MKDIR) webbrowser.app/Contents 
	@$(DEL_FILE) webbrowser.app/Contents/PkgInfo
	@echo "APPL????" >webbrowser.app/Contents/PkgInfo
webbrowser.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) webbrowser.app/Contents/Resources || $(MKDIR) webbrowser.app/Contents/Resources 
	@touch webbrowser.app/Contents/Resources/empty.lproj
	
webbrowser.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) webbrowser.app/Contents || $(MKDIR) webbrowser.app/Contents 
	@$(DEL_FILE) webbrowser.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,webbrowser,g" -e "s,@TYPEINFO@,????,g" ../../../QtSDK/Desktop/Qt/473/gcc/mkspecs/default/Info.plist.app >webbrowser.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/webbrowser1.0.0 || $(MKDIR) .tmp/webbrowser1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/webbrowser1.0.0/ && $(COPY_FILE) --parents qmlapplicationviewer/qmlapplicationviewer.h .tmp/webbrowser1.0.0/ && $(COPY_FILE) --parents main.cpp qmlapplicationviewer/qmlapplicationviewer.cpp .tmp/webbrowser1.0.0/ && (cd `dirname .tmp/webbrowser1.0.0` && $(TAR) webbrowser1.0.0.tar webbrowser1.0.0 && $(COMPRESS) webbrowser1.0.0.tar) && $(MOVE) `dirname .tmp/webbrowser1.0.0`/webbrowser1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/webbrowser1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r webbrowser.app
	-$(DEL_FILE) Makefile


first: $(first) copydeploymentfolders

copydeploymentfolders:
	@echo Copying application data... && $(MKDIR) "/Users/anskosti/workspace/qml/webbrowser/webbrowser.app/Contents/Resources/qml" && $(COPY_DIR) "/Users/anskosti/workspace/qml/webbrowser/qml" "/Users/anskosti/workspace/qml/webbrowser/webbrowser.app/Contents/Resources/qml" && $(MKDIR) "/Users/anskosti/workspace/qml/webbrowser/webbrowser.app/Contents/Resources/js" && $(COPY_DIR) "/Users/anskosti/workspace/qml/webbrowser/js" "/Users/anskosti/workspace/qml/webbrowser/webbrowser.app/Contents/Resources/js" && $(MKDIR) "/Users/anskosti/workspace/qml/webbrowser/webbrowser.app/Contents/Resources/images" && $(COPY_DIR) "/Users/anskosti/workspace/qml/webbrowser/images" "/Users/anskosti/workspace/qml/webbrowser/webbrowser.app/Contents/Resources/images"

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_qmlapplicationviewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qmlapplicationviewer.cpp
moc_qmlapplicationviewer.cpp: qmlapplicationviewer/qmlapplicationviewer.h
	/Users/anskosti/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ qmlapplicationviewer/qmlapplicationviewer.h -o moc_qmlapplicationviewer.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qmlapplicationviewer.o: qmlapplicationviewer/qmlapplicationviewer.cpp qmlapplicationviewer/qmlapplicationviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlapplicationviewer.o qmlapplicationviewer/qmlapplicationviewer.cpp

moc_qmlapplicationviewer.o: moc_qmlapplicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmlapplicationviewer.o moc_qmlapplicationviewer.cpp

####### Install

install_itemfolder_01: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/share/webbrowser/qml/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/share/webbrowser/qml/ 
	-$(INSTALL_DIR) /Users/anskosti/workspace/qml/webbrowser/qml $(INSTALL_ROOT)/usr/local/share/webbrowser/qml/


uninstall_itemfolder_01:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/webbrowser/qml/qml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/share/webbrowser/qml/ 


install_itemfolder_02: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/share/webbrowser/js/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/share/webbrowser/js/ 
	-$(INSTALL_DIR) /Users/anskosti/workspace/qml/webbrowser/js $(INSTALL_ROOT)/usr/local/share/webbrowser/js/


uninstall_itemfolder_02:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/webbrowser/js/js
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/share/webbrowser/js/ 


install_itemfolder_03: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/share/webbrowser/images/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/share/webbrowser/images/ 
	-$(INSTALL_DIR) /Users/anskosti/workspace/qml/webbrowser/images $(INSTALL_ROOT)/usr/local/share/webbrowser/images/


uninstall_itemfolder_03:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/share/webbrowser/images/images
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/share/webbrowser/images/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/local/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/local/bin/ 
	$(DEL_FILE) -r "$(INSTALL_ROOT)/usr/local/bin/webbrowser.app"
	
	-$(INSTALL_DIR) "webbrowser.app" "$(INSTALL_ROOT)/usr/local/bin/webbrowser.app"

uninstall_target:  FORCE
	-$(DEL_FILE) -r "$(INSTALL_ROOT)/usr/local/bin/webbrowser.app"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/bin/ 


install:  install_itemfolder_01 install_itemfolder_02 install_itemfolder_03 install_target  FORCE

uninstall: uninstall_itemfolder_01 uninstall_itemfolder_02 uninstall_itemfolder_03 uninstall_target   FORCE

FORCE:

