#############################################################################
# Makefile for building: webbrowser.app/Contents/MacOS/webbrowser
# Generated by qmake (2.01a) (Qt 4.7.1) on: ke marraskuuta 24 14:21:32 2010
# Project:  webbrowser.pro
# Template: app app
# Command: /usr/local/Trolltech/Qt-4.7.1/bin/qmake -o Makefile webbrowser.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.7.1/mkspecs/macx-g++ -I. -I/usr/local/Trolltech/Qt-4.7.1/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.7.1/include/QtCore -I/usr/local/Trolltech/Qt-4.7.1/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.7.1/include/QtGui -I/usr/local/Trolltech/Qt-4.7.1/lib/QtDeclarative.framework/Versions/4/Headers -I/usr/local/Trolltech/Qt-4.7.1/include/QtDeclarative -I/usr/local/Trolltech/Qt-4.7.1/include -I. -F/usr/local/Trolltech/Qt-4.7.1/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/usr/local/Trolltech/Qt-4.7.1/lib -L/usr/local/Trolltech/Qt-4.7.1/lib -framework QtDeclarative -L/usr/local/Trolltech/Qt-4.7.1/lib -F/usr/local/Trolltech/Qt-4.7.1/lib -framework QtScript -framework QtCore -framework QtSvg -framework QtGui -framework QtSql -framework QtXmlPatterns -framework QtNetwork -framework QtOpenGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/Trolltech/Qt-4.7.1/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = /usr/local/Trolltech/Qt-4.7.1/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/common/mac-g++.conf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/x86_64.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/rez.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/include_source_dir.prf \
		webbrowser.pro
QMAKE_TARGET  = webbrowser
DESTDIR       = 
TARGET        = webbrowser.app/Contents/MacOS/webbrowser

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile webbrowser.app/Contents/PkgInfo webbrowser.app/Contents/Resources/empty.lproj webbrowser.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) webbrowser.app/Contents/MacOS/ || $(MKDIR) webbrowser.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: webbrowser.pro  /usr/local/Trolltech/Qt-4.7.1/mkspecs/macx-g++/qmake.conf /usr/local/Trolltech/Qt-4.7.1/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/common/mac-g++.conf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/x86_64.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/rez.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.7.1/lib/QtDeclarative.framework/QtDeclarative.prl \
		/usr/local/Trolltech/Qt-4.7.1/lib/QtScript.framework/QtScript.prl \
		/usr/local/Trolltech/Qt-4.7.1/lib/QtCore.framework/QtCore.prl \
		/usr/local/Trolltech/Qt-4.7.1/lib/QtSvg.framework/QtSvg.prl \
		/usr/local/Trolltech/Qt-4.7.1/lib/QtGui.framework/QtGui.prl \
		/usr/local/Trolltech/Qt-4.7.1/lib/QtSql.framework/QtSql.prl \
		/usr/local/Trolltech/Qt-4.7.1/lib/QtXmlPatterns.framework/QtXmlPatterns.prl \
		/usr/local/Trolltech/Qt-4.7.1/lib/QtNetwork.framework/QtNetwork.prl \
		/usr/local/Trolltech/Qt-4.7.1/lib/QtOpenGL.framework/QtOpenGL.prl
	$(QMAKE) -o Makefile webbrowser.pro
/usr/local/Trolltech/Qt-4.7.1/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/common/mac.conf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/common/mac-g++.conf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/default_pre.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/dwarf2.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/default_post.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/x86_64.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/objective_c.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/rez.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/mac/sdk.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.7.1/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.7.1/lib/QtDeclarative.framework/QtDeclarative.prl:
/usr/local/Trolltech/Qt-4.7.1/lib/QtScript.framework/QtScript.prl:
/usr/local/Trolltech/Qt-4.7.1/lib/QtCore.framework/QtCore.prl:
/usr/local/Trolltech/Qt-4.7.1/lib/QtSvg.framework/QtSvg.prl:
/usr/local/Trolltech/Qt-4.7.1/lib/QtGui.framework/QtGui.prl:
/usr/local/Trolltech/Qt-4.7.1/lib/QtSql.framework/QtSql.prl:
/usr/local/Trolltech/Qt-4.7.1/lib/QtXmlPatterns.framework/QtXmlPatterns.prl:
/usr/local/Trolltech/Qt-4.7.1/lib/QtNetwork.framework/QtNetwork.prl:
/usr/local/Trolltech/Qt-4.7.1/lib/QtOpenGL.framework/QtOpenGL.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile webbrowser.pro

webbrowser.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) webbrowser.app/Contents || $(MKDIR) webbrowser.app/Contents 
	@$(DEL_FILE) webbrowser.app/Contents/PkgInfo
	@echo "APPL????" >webbrowser.app/Contents/PkgInfo
webbrowser.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) webbrowser.app/Contents/Resources || $(MKDIR) webbrowser.app/Contents/Resources 
	@touch webbrowser.app/Contents/Resources/empty.lproj
	
webbrowser.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) webbrowser.app/Contents || $(MKDIR) webbrowser.app/Contents 
	@$(DEL_FILE) webbrowser.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,webbrowser,g" -e "s,@TYPEINFO@,????,g" /usr/local/Trolltech/Qt-4.7.1/mkspecs/macx-g++/Info.plist.app >webbrowser.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/webbrowser1.0.0 || $(MKDIR) .tmp/webbrowser1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/webbrowser1.0.0/ && $(COPY_FILE) --parents main.cpp .tmp/webbrowser1.0.0/ && (cd `dirname .tmp/webbrowser1.0.0` && $(TAR) webbrowser1.0.0.tar webbrowser1.0.0 && $(COMPRESS) webbrowser1.0.0.tar) && $(MOVE) `dirname .tmp/webbrowser1.0.0`/webbrowser1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/webbrowser1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r webbrowser.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

